name: Deploy Site on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🚀 Deploy website on push (main)
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD}}
          exclude: |
            **/.git*
            **/.DS_Store*
            **/.git*/**
